export const COLORS = [
  'primary',
  'secondary',
  'success',
  'info',
  'error',
  'warning',
  // 'black',
  // 'slate',
  // 'gray',
  // 'zinc',
  // 'neutral',
  // 'stone',
  // 'red',
  // 'orange',
  // 'amber',
  // 'yellow',
  // 'lime',
  // 'green',
  // 'emerald',
  // 'teal',
  // 'cyan',
  // 'sky',
  // 'indigo',
  // 'violet',
  // 'purple',
  // 'fuchsia',
  // 'pink',
  // 'rose',
] as const;

export type ColorType = typeof COLORS[number]